// <auto-generated />
using System;
using ExamCompanion.Infrastructure.Music;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamCompanion.Infrastructure.Music.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260912183618_PreserveSuspendedQuestionDuringRepair")]
    partial class PreserveSuspendedQuestionDuringRepair
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ExamCompanion.Domain.Music.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChallengeAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCycleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CurrentQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CurrentTopicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EducationalAnswered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EducationalTarget")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RepairEducationalCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RepairTopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SuspendedQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuspendedStep")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StartedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Type", "SourceId")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.QuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasReinforcement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasRepair")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("GameSessionId", "TurnId")
                        .IsUnique();

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Importance")
                        .HasColumnType("REAL");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicalColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("Topics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Topic_Importance", "Importance >= 0 AND Importance <= 1");
                        });
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.TopicProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedCycles")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasScratch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepaired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReinforcementCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredCycles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWrongAnswers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("GameSessionId", "TopicId")
                        .IsUnique();

                    b.ToTable("TopicProgress");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.GameSession", b =>
                {
                    b.HasOne("ExamCompanion.Domain.Music.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Question", b =>
                {
                    b.HasOne("ExamCompanion.Domain.Music.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.QuestionAttempt", b =>
                {
                    b.HasOne("ExamCompanion.Domain.Music.GameSession", null)
                        .WithMany("Attempts")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamCompanion.Domain.Music.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Topic", b =>
                {
                    b.HasOne("ExamCompanion.Domain.Music.Lesson", "Lesson")
                        .WithMany("Topics")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.TopicProgress", b =>
                {
                    b.HasOne("ExamCompanion.Domain.Music.GameSession", null)
                        .WithMany("Topics")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamCompanion.Domain.Music.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.GameSession", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Lesson", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ExamCompanion.Domain.Music.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
