// <auto-generated />
using System;
using ChallengePrototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChallengePrototype.Data.Migrations
{
    [DbContext(typeof(ChallengeDbContext))]
    partial class ChallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ChallengePrototype.Models.ChallengeLevelProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChallengeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentHealth")
                        .HasColumnType("REAL");

                    b.Property<int>("EvidenceCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvidenceRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsAnswered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartingHealth")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetQuestionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonChallengeId", "ChallengeLevel")
                        .IsUnique();

                    b.ToTable("LevelProgresses");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ChallengeRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EndHealth")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LevelProgressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartHealth")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StopReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LevelProgressId", "RunNumber")
                        .IsUnique();

                    b.ToTable("ChallengeRuns");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ExamLessonChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExamSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LevelDesignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelDesignVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LevelDesignId");

                    b.HasIndex("ExamSessionId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonChallenges");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ExamSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("ChallengePrototype.Models.LevelDesign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("LevelDesigns");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Default Challenge Design",
                            Version = 1
                        });
                });

            modelBuilder.Entity("ChallengePrototype.Models.LevelRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageQuestionsPerTopic")
                        .HasColumnType("REAL");

                    b.Property<int>("ChallengeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EasyQuestionWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("FailureHealth")
                        .HasColumnType("REAL");

                    b.Property<double>("HardQuestionWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("ImportanceFocus")
                        .HasColumnType("REAL");

                    b.Property<long>("LevelDesignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumQuestionsPerTopic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumTotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MediumQuestionWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("MinimumEvidencePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumQuestionsPerTopic")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PromotionHealth")
                        .HasColumnType("REAL");

                    b.Property<double>("StartingHealth")
                        .HasColumnType("REAL");

                    b.Property<double>("VeryHardQuestionWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LevelDesignId", "ChallengeLevel")
                        .IsUnique();

                    b.ToTable("LevelRules", t =>
                        {
                            t.HasCheckConstraint("CK_LevelRule_Evidence", "MinimumEvidencePercent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_LevelRule_QuestionLimits", "MinimumQuestionsPerTopic > 0 AND MaximumQuestionsPerTopic >= MinimumQuestionsPerTopic");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AverageQuestionsPerTopic = 1.6000000000000001,
                            ChallengeLevel = 0,
                            EasyQuestionWeight = 0.5,
                            FailureHealth = 0.0,
                            HardQuestionWeight = 0.20000000000000001,
                            ImportanceFocus = 1.0,
                            LevelDesignId = 1L,
                            MaximumQuestionsPerTopic = 3,
                            MaximumTotalQuestions = 24,
                            MediumQuestionWeight = 0.20000000000000001,
                            MinimumEvidencePercent = 75,
                            MinimumQuestionsPerTopic = 1,
                            PromotionHealth = 100.0,
                            StartingHealth = 50.0,
                            VeryHardQuestionWeight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 2L,
                            AverageQuestionsPerTopic = 2.0,
                            ChallengeLevel = 1,
                            EasyQuestionWeight = 0.25,
                            FailureHealth = 0.0,
                            HardQuestionWeight = 0.25,
                            ImportanceFocus = 1.25,
                            LevelDesignId = 1L,
                            MaximumQuestionsPerTopic = 3,
                            MaximumTotalQuestions = 28,
                            MediumQuestionWeight = 0.40000000000000002,
                            MinimumEvidencePercent = 75,
                            MinimumQuestionsPerTopic = 1,
                            PromotionHealth = 100.0,
                            StartingHealth = 50.0,
                            VeryHardQuestionWeight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 3L,
                            AverageQuestionsPerTopic = 2.3999999999999999,
                            ChallengeLevel = 2,
                            EasyQuestionWeight = 0.14999999999999999,
                            FailureHealth = 0.0,
                            HardQuestionWeight = 0.45000000000000001,
                            ImportanceFocus = 1.5,
                            LevelDesignId = 1L,
                            MaximumQuestionsPerTopic = 4,
                            MaximumTotalQuestions = 32,
                            MediumQuestionWeight = 0.20000000000000001,
                            MinimumEvidencePercent = 75,
                            MinimumQuestionsPerTopic = 1,
                            PromotionHealth = 100.0,
                            StartingHealth = 50.0,
                            VeryHardQuestionWeight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 4L,
                            AverageQuestionsPerTopic = 2.7999999999999998,
                            ChallengeLevel = 3,
                            EasyQuestionWeight = 0.050000000000000003,
                            FailureHealth = 0.0,
                            HardQuestionWeight = 0.29999999999999999,
                            ImportanceFocus = 1.8,
                            LevelDesignId = 1L,
                            MaximumQuestionsPerTopic = 4,
                            MaximumTotalQuestions = 32,
                            MediumQuestionWeight = 0.14999999999999999,
                            MinimumEvidencePercent = 75,
                            MinimumQuestionsPerTopic = 1,
                            PromotionHealth = 100.0,
                            StartingHealth = 50.0,
                            VeryHardQuestionWeight = 0.5
                        });
                });

            modelBuilder.Entity("ChallengePrototype.Models.QuestionAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveThinkingMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualQuestionDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AnswerHealthDelta")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChallengeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChallengeRunId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HealthAfter")
                        .HasColumnType("REAL");

                    b.Property<double>("HealthBefore")
                        .HasColumnType("REAL");

                    b.Property<int>("ImportanceSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ShownAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeHealthDelta")
                        .HasColumnType("REAL");

                    b.Property<long>("TopicProgressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicProgressId");

                    b.HasIndex("ChallengeRunId", "QuestionId");

                    b.ToTable("QuestionAttempts");
                });

            modelBuilder.Entity("ChallengePrototype.Models.TopicProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportanceSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LessonChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBonusEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonChallengeId", "TopicId")
                        .IsUnique();

                    b.ToTable("TopicProgresses", t =>
                        {
                            t.HasCheckConstraint("CK_TopicProgress_Importance", "ImportanceSnapshot BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ChallengePrototype.Models.ChallengeLevelProgress", b =>
                {
                    b.HasOne("ChallengePrototype.Models.ExamLessonChallenge", "LessonChallenge")
                        .WithMany("LevelProgresses")
                        .HasForeignKey("LessonChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonChallenge");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ChallengeRun", b =>
                {
                    b.HasOne("ChallengePrototype.Models.ChallengeLevelProgress", "LevelProgress")
                        .WithMany("ChallengeRuns")
                        .HasForeignKey("LevelProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelProgress");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ExamLessonChallenge", b =>
                {
                    b.HasOne("ChallengePrototype.Models.ExamSession", "ExamSession")
                        .WithMany("LessonChallenges")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChallengePrototype.Models.LevelDesign", "LevelDesign")
                        .WithMany()
                        .HasForeignKey("LevelDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("LevelDesign");
                });

            modelBuilder.Entity("ChallengePrototype.Models.LevelRule", b =>
                {
                    b.HasOne("ChallengePrototype.Models.LevelDesign", "LevelDesign")
                        .WithMany("LevelRules")
                        .HasForeignKey("LevelDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelDesign");
                });

            modelBuilder.Entity("ChallengePrototype.Models.QuestionAttempt", b =>
                {
                    b.HasOne("ChallengePrototype.Models.ChallengeRun", "ChallengeRun")
                        .WithMany("QuestionAttempts")
                        .HasForeignKey("ChallengeRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChallengePrototype.Models.TopicProgress", "TopicProgress")
                        .WithMany()
                        .HasForeignKey("TopicProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChallengeRun");

                    b.Navigation("TopicProgress");
                });

            modelBuilder.Entity("ChallengePrototype.Models.TopicProgress", b =>
                {
                    b.HasOne("ChallengePrototype.Models.ExamLessonChallenge", "LessonChallenge")
                        .WithMany("TopicProgresses")
                        .HasForeignKey("LessonChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonChallenge");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ChallengeLevelProgress", b =>
                {
                    b.Navigation("ChallengeRuns");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ChallengeRun", b =>
                {
                    b.Navigation("QuestionAttempts");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ExamLessonChallenge", b =>
                {
                    b.Navigation("LevelProgresses");

                    b.Navigation("TopicProgresses");
                });

            modelBuilder.Entity("ChallengePrototype.Models.ExamSession", b =>
                {
                    b.Navigation("LessonChallenges");
                });

            modelBuilder.Entity("ChallengePrototype.Models.LevelDesign", b =>
                {
                    b.Navigation("LevelRules");
                });
#pragma warning restore 612, 618
        }
    }
}
